/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import entidades.Doctor;
import entidades.Paciente;
import entidades.Persona;
import javax.swing.JOptionPane;
import principal.Principal;

/**
 *
 * @author lauza
 */
public class Turno extends javax.swing.JFrame {

    /**
     * Creates new form Turno
     */
    public Turno() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelPac = new javax.swing.JLabel();
        labelDoc = new javax.swing.JLabel();
        labelTurno = new javax.swing.JLabel();
        labelMot = new javax.swing.JLabel();
        buttPac = new javax.swing.JButton();
        buttDoc = new javax.swing.JButton();
        fieldFec = new javax.swing.JTextField();
        fieldDoc = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        areaPac = new javax.swing.JTextArea();
        fieldPac = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        areaDoc = new javax.swing.JTextArea();
        fieldHora = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labelFec = new javax.swing.JLabel();
        fieldMot = new javax.swing.JTextField();
        buttConf = new javax.swing.JButton();
        buttCanc = new javax.swing.JButton();
        buttMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cargar turno");
        setLocationByPlatform(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelPac.setText("PACIENTE");
        jPanel1.add(labelPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 81, -1));

        labelDoc.setText("DOCTOR");
        jPanel1.add(labelDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 55, 23));

        labelTurno.setText("TURNO");
        jPanel1.add(labelTurno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 48, 22));

        labelMot.setText("MOTIVO DE CONSULTA");
        jPanel1.add(labelMot, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 170, -1));

        buttPac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        buttPac.setText("Id Paciente");
        buttPac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttPacActionPerformed(evt);
            }
        });
        jPanel1.add(buttPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 28, -1, -1));

        buttDoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search.png"))); // NOI18N
        buttDoc.setText("Id Doctor");
        buttDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttDocActionPerformed(evt);
            }
        });
        jPanel1.add(buttDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 111, -1));
        jPanel1.add(fieldFec, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 134, -1));
        jPanel1.add(fieldDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 171, -1));

        areaPac.setColumns(20);
        areaPac.setRows(5);
        jScrollPane3.setViewportView(areaPac);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 570, 30));
        jPanel1.add(fieldPac, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 171, -1));

        areaDoc.setColumns(20);
        areaDoc.setRows(5);
        jScrollPane4.setViewportView(areaDoc);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 150, 570, 29));

        fieldHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHoraActionPerformed(evt);
            }
        });
        jPanel1.add(fieldHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 134, -1));

        jLabel1.setText("Hora");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 73, 20));

        labelFec.setText("Fecha");
        jPanel1.add(labelFec, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 48, -1));
        jPanel1.add(fieldMot, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 570, -1));

        buttConf.setText("Confirmar");
        jPanel1.add(buttConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 110, -1));

        buttCanc.setText("Cancelar");
        jPanel1.add(buttCanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 120, -1));

        buttMenu.setText("MENU");
        jPanel1.add(buttMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttPacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttPacActionPerformed

//        Integer idPaciente = Integer.parseInt(fieldPac.getText());
//        Persona per = new Persona();
//        Paciente pac = (Paciente) per;
//        pac.setIdPaciente(idPaciente); 
//        Principal.buscarPacientePorId(per, this);
//        areaPac.add(this);
        Integer idPaciente = Integer.parseInt(fieldPac.getText());

        Paciente pac = new Paciente();
        pac.setIdPaciente(idPaciente);

        Paciente perMod = Principal.buscarPacientePorId(pac, this);

        areaPac.setText(perMod.toString());


    }//GEN-LAST:event_buttPacActionPerformed

    private void fieldHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHoraActionPerformed

    private void buttDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttDocActionPerformed
        Integer idDoctor = Integer.parseInt(fieldDoc.getText());
        Persona per = new Persona();
        Doctor doc = (Doctor) per;
        doc.setIdDoctor(idDoctor);
        Principal.buscarDoctorPorId(per, this);
     //   jTextField1.add(this);

    }//GEN-LAST:event_buttDocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDoc;
    private javax.swing.JTextArea areaPac;
    private javax.swing.JButton buttCanc;
    private javax.swing.JButton buttConf;
    private javax.swing.JButton buttDoc;
    private javax.swing.JButton buttMenu;
    private javax.swing.JButton buttPac;
    private javax.swing.JTextField fieldDoc;
    private javax.swing.JTextField fieldFec;
    private javax.swing.JTextField fieldHora;
    private javax.swing.JTextField fieldMot;
    private javax.swing.JTextField fieldPac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelDoc;
    private javax.swing.JLabel labelFec;
    private javax.swing.JLabel labelMot;
    private javax.swing.JLabel labelPac;
    private javax.swing.JLabel labelTurno;
    // End of variables declaration//GEN-END:variables
}
